version: '3.8'

services:
  # Zookeeper Service
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_origin
    environment:
      ZOOKEEPER_CLIENT_PORT: 50001
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "50001:50001"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "50001"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - my_network

  # Kafka Service
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "50008:50008"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:50001
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:50008,PLAINTEXT_INTERNAL://0.0.0.0:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://35.193.215.248:50008,PLAINTEXT_INTERNAL://kafka:29092
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "50008"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - my_network

  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "50003:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: ["--port", "27017"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    networks:
      - my_network

  # MinIO Service
  minio:
    image: minio/minio:latest
    container_name: minio_origin
    ports:
      - "50004:9000"
      - "50005:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - my_network

  # PostgreSQL Service
  postgres:
    image: postgres:latest
    container_name: postgres_origin
    ports:
      - "50007:5432"  # Custom external port for PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost", "-p", "5432"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - my_network

volumes:
  mongo_data:

networks:
  my_network:
    driver: bridge
